const menu = [
  {
    id: 1,
    title: "Pancakes with Maple Syrup",
    category: "breakfast",
    price: 15.99,
    img: "./images/item-1.jpeg",
    desc: "Vanilla pancakes with Canadian maple syrup, blueberries, strawberries and bananas; bowl of fresh fruit; natural yogurt with mango sounds delicious!",
  },
  {
    id: 2,
    title: "diner double",
    category: "lunch",
    price: 13.99,
    img: "./images/item-2.jpeg",
    desc: "Double burger with double patties of your own choice of meat with the side of french fries along with the sauce is yummilicious!",
  },
  {
    id: 3,
    title: "godzilla milkshake",
    category: "shakes",
    price: 6.99,
    img: "./images/item-3.jpeg",
    desc: "Yummy milkshake with the choice of your favorite flavors, topped with the donuts, icecream and whipped cream with cherries and sprinkler of your choice!",
  },
  {
    id: 4,
    title: "country delight",
    category: "breakfast",
    price: 20.99,
    img: "./images/item-4.jpeg",
    desc: "It's a perfect breakfast which consists of toast with the omlette along with the omlette and fries and cheese!",
  },
  {
    id: 5,
    title: "egg attack",
    category: "lunch",
    price: 22.99,
    img: "./images/item-5.jpeg",
    desc: "Egg monster sandwitch with the egg stuffing along with the delicious sauces along with the frappe!",
  },
  {
    id: 6,
    title: "oreo dream",
    category: "shakes",
    price: 18.99,
    img: "./images/item-6.jpeg",
    desc: "Orea shake with exotic flavors of your choice of amazing oreo!",
  },
  {
    id: 7,
    title: "bacon overflow",
    category: "breakfast",
    price: 8.99,
    img: "./images/item-7.jpeg",
    desc: "Bacon with double egg omlette along with the cheesy layer and spinach!",
  },
  {
    id: 8,
    title: "american classic",
    category: "lunch",
    price: 12.99,
    img: "./images/item-8.jpeg",
    desc: "The classic American favourite is here!! A burger with stuffing of meat of your choice along the classic fries is mouthwatering!",
  },
  {
    id: 9,
    title: "quarantine buddy",
    category: "shakes",
    price: 16.99,
    img: "./images/item-9.jpeg",
    desc: "A special shake with the chocochips and vanilla and creamy layer with the flavor of your choice for this quarantine period!",
  },
];
export default menu;
